version: '3'

services:
  db:
    restart: always
    image: postgres:15.2
    container_name: docer-postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
